/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_encdemo_LoadNative */

#ifndef _Included_com_example_encdemo_LoadNative
#define _Included_com_example_encdemo_LoadNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_encdemo_LoadNative
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_encdemo_LoadNative_encrypt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_encdemo_LoadNative
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_encdemo_LoadNative_decrypt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
