/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mytime_myData */

#ifndef _Included_com_example_mytime_myData
#define _Included_com_example_mytime_myData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mytime_myData
 * Method:    mydata
 * Signature: (I)I
 */
/**
JNIEXPORT jstring JNICALL Java_com_example_aesbase64enc_MainActivity_encData
  (JNIEnv *, jobject, jstring);

JNIEXPORT jstring JNICALL Java_com_example_aesbase64enc_MainActivity_decData
  (JNIEnv *, jobject, jstring);**/
#ifdef __cplusplus
}
#endif
#endif
